export { default as Product } from "./Product.component"
export { default as ProductList } from "./ProductList.component"
export { default as UserList } from "./UserList.component"
export { default as DataTable } from "./DataTable.component"
export { default as Navbar } from "./Navbar.component"
